experiment_name: "simu_cifar10_siren"
output_dir: "./outputs"

simu_data:
  source_img: "./cifar10"
  speckle_format: "png"
  source_size: 32
  speckle_size: 256
  seed: 3047
  pupil_radius: 0.5
  supp_size_w: 32
  supp_size_h: 32

data:
  path: "./num_mask"
  format: "tif"
  ori_size: 2048
  crop_size: 1024
  desired_size: 512
  blur_kernel_size: 21
  sigma: 3.0
  supp_size_w: 60
  supp_size_h: 40

model:
  type: "SIREN"
  in_features: 2
  hidden_layers: 2
  hidden_features: 128
  out_features: 1
  first_omega_0: 30
  hidden_omega_0: 30
  outermost_linear: True
  num_frequencies: 8


training:
  random_seed: true
  seed: 5067
  device: "cuda"  # or "cpu"
  epochs: 5000
  optimizer: "Adam"  # or "SGD"
  lr: !!float 1e-4
  loss: "L1"  # or "MSE"
  center_sample: false
  center_sample_radius: 0.5
  random_sample: false
  random_sample_ratio: 0.1

  tv_regularization: false
  tv_weight: !!float 1e-4

  num_frames: 5
